web:
  chromeOptions:
    args:
      - --no-sandbox
      - --disable-dev-shm-usage
      - --disable-gpu
      - --headless
      - --remote-debugging-port=0
      - --disable-background-timer-throttling
      - --disable-backgrounding-occluded-windows
      - --disable-renderer-backgrounding
      - --user-data-dir=/tmp/maestro-chrome-${RANDOM}