name: Integration Tests Android

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

jobs:
  build-preview:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: ğŸ— Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ›  Setup development environment
        uses: ./.github/actions/setup-dev-environment
        with:
          devbox-config: android-build

      - name: Build
        working-directory: devbox/android-build
        run: devbox run build_preview

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: preview_build
          path: build_preview.apk

  integration-tests-android:
    runs-on: ubuntu-latest
    needs: build-preview
    steps:
      - name: ğŸ— Checkout repository
        uses: actions/checkout@v4

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: preview_build

      - name: ğŸ›  Setup testing environment
        uses: ./.github/actions/setup-dev-environment
        with:
          devbox-config: android-testing

      - name: Run tests
        working-directory: devbox/android-testing
        run: devbox run integration_test_android

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-integration-test-debug-artifacts
          path: |
            maestro-debug-output/
            *.png
            *.xml
            devbox/android-testing/maestro-debug-output/
          retention-days: 14
